<template>
    <div>
        首页
        <div>首页</div>
         <div>首页</div>
          <div>首页</div>
           <div>首页</div>
            <div>首页</div>
             <div>首页</div>
              <div>首页</div>
               <div>首页</div>
                <div>首页</div>
                 <div>首页</div>
                  <div>首页</div>
    </div>
</template>